apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-data
  namespace: mongo
  labels:
    type: local
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/data/db"